version: '3'
services:
  redis:
    image: redis
    container_name: redisIoT
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    entrypoint: redis-server --appendonly yes
    network_mode: "host"
    restart: always
  kvserver:
    image: kvserver
    container_name: kvdocker
    ports:
      - "5000:5000"
    entrypoint: "gunicorn -w 4 -b 0.0.0.0:5000 server:app" 
    network_mode: "host"
    restart: always  
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
    ports:
      - 80:80
      - 443:443
