version: '2.1'
services:
  redis:
    image: redis
    container_name: redis
    mem_limit: 200m
    mem_reservation: 10m
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    entrypoint: redis-server --appendonly yes
    network_mode: "host"
    restart: "no"
  kvserver:
    image: kvserver
    container_name: server
    mem_limit: 100m
    mem_reservation: 70m
    ports:
      - "5000:5000"
    volumes:
      - ./flask/config.json:/etc/kviot.json
    entrypoint: "gunicorn -w 4 -b 127.0.0.1:5000 server:app" 
    network_mode: "host"
    restart: "no"  
  nginx:
    image: nginx
    container_name: nginx
    mem_limit: 30m
    mem_reservation: 10m
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
    network_mode: "host"
    restart: "no"
    logging:
      driver: "json-file"
    ports:
      - 80:80
      - 443:443
